version: '3.7'

services: 
  db:
    image: postgres
    container_name: db_prisma
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=prisma
    volumes: 
      - pgdata:/data/postgres
  app:
    build: .
    container_name: koa-prisma
    ports:
      - 3333:3333
    volumes: 
      - .:/usr/app
volumes: 
  pgdata:
    driver: local
    